@startuml

rectangle 映画 {
 object "映画" as movie {
    映画ID
    タイトル
 }
 object "映画ギミック" as gimmick {
    ギミックなし/3D作品
 }

 gimmick "1" - "1" movie
}

rectangle スクリーン as screenRepo {
 object "スクリーン" as screen {
    スクリーンID
    スクリーン名
 }
 object "座席" as sheet {
    座席ID
    座席名
 }
 sheet "many" - "1" screen
}
note bottom of screenRepo : 今回は実装の対象外

rectangle 上映スケジュール {
 object "上映スケジュール" as schedule {
    上映ID
    映画
    上映日
    上映開始時間
 }
 object "特別上映" as special {
    特別興行/爆音上映
 }
 schedule "1" - "1" special
}
note top of schedule : ・毎月1日は映画の日\n・映画の日は、エムアイカードと\n　駐車場パーク80割引は適用外\n・20時以降の上映はレイトショー


rectangle チケット料金 {
 object "チケット料金" as ticketPrice {
    合計金額
 }
 object "チケット" as ticket {
    チケットID
    料金
    枚数
 }
ticket "1" - "many" ticketPrice
}

rectangle 顧客 {
 object "顧客" as customer {
    生年月日
    証明書
    会員証
 }
 object "証明書" as certificate {
    身分証/学生証/生徒手帳/障害者手帳
 }
 object "会員証" as member {
    会員ID
 }
 object "3Dメガネ" as 3dglass {
    あり/なし
 }
 certificate "1" -- "1" customer
 member "1" -- "1" customer
 3dglass "1" -- "1" customer
}
note bottom of customer : 中・高校生は生徒手帳\n学生（大・専）は学生証\nシニア（70才以上）は身分証\n障がい者（学生以上）は障害者手帳\n障がい者（高校以下）は、障害者手帳と生徒手帳\nで身分を確認し、料金を適用する

rectangle 料金表 {
 object "料金表" as priceList {
  料金ID
  料金名
  料金
 }
}

movie -[hidden]- screen
priceList -[hidden]- ticket

movie "1" - "many" schedule
screen "1" - "1" schedule

schedule "1" - "1" ticket
schedule "1" -- "1" priceList
customer "1" - "1" priceList
priceList "1" -- "1" ticket
sheet "1" - "1" ticket
@enduml
